graphql:
  tools:
    schemaLocationPattern: graphql/default.graphqls,graphql/share/*.graphqls
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  multiEndpoints:
      client:
        schemaLocationPattern: graphql/client.graphqls,graphql/share/*.graphqls
        endpoint: /client